language: php

php:
  - '7.0'
  - '7.1'

env:
  - 'TYPO3_VERSION="^8.7.0"'

before_script:
  - 'export TYPO3_PATH_WEB=$PWD/.Build/Web'

install:
  - 'composer require typo3/cms="$TYPO3_VERSION"'
  - 'git checkout composer.json'

sudo: false

script:
  - '.Build/bin/phpcpd Classes/ --min-tokens=42'
  - '.Build/bin/phpcs Classes/ --standard=PSR2'
#  - '.Build/bin/phpmd Classes/ text cleancode'
#  - '.Build/bin/phpmd Classes/ text codesize'
  - '.Build/bin/phpmd Classes/ text controversial'
  - '.Build/bin/phpmd Classes/ text design'
  - '.Build/bin/phpmd Classes/ text naming'
  - '.Build/bin/phpmd Classes/ text unusedcode'
  - '.Build/bin/phpunit -c phpunit.xml.dist'

cache:
  directories:
    - '$HOME/.composer/cache'

notifications:
  slack:
    rooms:
      secure: IpPecoMtl6NINmS75VuRpv7mi2ax8tGV1u6E2RVfGeHB3qYmknoxFIXvAQnEAD1VtG1uTwOUTJbFNd7LABZOILfWoX9d2KS7A0vT5FjTZIlQv4htFl0FJN1zsWNQ7qlOy2JTNbJk7AtvlbQKjx1j594dWKOszLiGHoEcVGezlzwTGPRTHVQx5cHfkP3CFXtKaCwv1+VvDOrBAOU8J4iRyhPgP+8IzOVOGZjkvY2/QxCfh9fS7jnoOwNMHvYCCyuRVYJPtZt5pMeEHNI/EfMORgZnlp5hAeTANBtry1i5WrrkyFPwrU6wQb39kJGfhj2s7hJr7wYwT0Xvn+sOF+5KTLEYjtKHhuno6VXLxrujBRjuK7oHErUGH8ly/u67ccJQwnuKngY2+k+G/JB/7ciNArGW+WjiXeWCiUJN7+GDz0U0cZ3ibdcJGp9+Fg+RDZjebZotfrFMmGXE9RzVSFrp1tZUcskhTatZ2S7ReaQ8R7wK7xMTDdDrLWqPKNJM73BAtoyZDcm/nc81+e3VUhSRjAhLvQgp8bXr95LqV4hBbhipnUOU4EWlpEcsFyOPk9Cb/ZYPRNimcbpzdZKt5bA42BVpzk6pf0QB+1Eo9OEmqWJIm+71/6jrLTr4lah7RFxwctYIWCg3gsDp1i+0lke0UpLzk4cIV4cGgiEvdwiXSk4=
    on_success: change
    on_failure: always
  email:
    on_success: never
    on_failure: change
